### ISSUE TITLE
Git clone command fails 

### ISSUE THREAD

**Issue by raducara** [TexasInstruments/ti-docker-images#11]
Please update README. I have issues with "git clone https://git.ti.com/git/arago-project/oe-layersetup.git tisdk". 
The link gives error when cloning.

Thanks.

**Comment by cshilwant** [comment]
@raducara Can you share the logs that you are observing?
As the command works perfectly fine on my system

`chirag@chirag-HP-Z2-Tower-G5-Workstation:~$ git clone https://git.ti.com/git/arago-project/oe-layersetup.git tisdk
Cloning into 'tisdk'...
remote: Enumerating objects: 2998, done.
remote: Counting objects: 100% (2998/2998), done.
remote: Compressing objects: 100% (955/955), done.
remote: Total 2998 (delta 2283), reused 2645 (delta 1981), pack-reused 0
Receiving objects: 100% (2998/2998), 457.92 KiB | 1.92 MiB/s, done.
Resolving deltas: 100% (2283/2283), done.
`

**Comment by cshilwant** [comment]
Closing this issue as it's not reproducible
